site_name: My Docs
#nav:
#  - 主页:
#    - 欢迎来到我的博客: index.md
#  - 技术学习: 
#    - 技术学习简介: technology_learn/index.md
#  - 书籍阅读: 
#    - 书籍阅读简介: book_read/index.md
#  - 日常生活: 
#    - 日常生活简介: daily_life/index.md
#  - 杂记:
#    - 杂记简介: miscellany/index.md
#    - HR面汇总: miscellany/the_hr_interview.md
#    - HR面谈薪资: miscellany/talks_about_salary.md
#  - About: about.md

nav:
  - 主页:
    - 欢迎来到我的博客: index.md
  - 技术学习: 
    - 技术学习简介: technology_learn/index.md
  - 书籍阅读: 
    - 书籍阅读简介: book_read/index.md
  - 日常生活: 
    - 日常生活简介: daily_life/index.md
  - 杂记:
    - 杂记简介: miscellany/index.md
    - HR面汇总: miscellany/the_hr_interview.md
    - HR面谈薪资: miscellany/talks_about_salary.md
    - 克制消费: miscellany/restrain_consumption.md
  - About: about.md
#nav:
#  - Blog:
#    - index.md

theme:
  name: material
  #custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false  # 不单独生成搜索结果页（依赖主题内置搜索）
  search_index_only: true  # 搜索仅索引内容，可能提升性能
  #favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:  # 启用的主题功能
    - content.action.edit  # 显示“编辑本页”按钮（需结合仓库地址配置）
    - navigation.tabs      # 导航栏 tabs 功能（多页面分组显示）
    - navigation.instant   # 页面切换无刷新（Instant Loading 增强体验）
   # - navigation.indexes   # 章节索引页，文档可以直接附加到章节
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins:
  - blog # 设置博客插件  
